name: NestJS - Build

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'release-*'

jobs:
  build:
    name: Production Build
    runs-on: ubuntu-latest # [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
      - run: npm run-script build
      - run: npm run-script test